version: 2.1
executors:
  ci-executor:
      docker:
        - image: conda/miniconda3

jobs:
  executor: ci-executor
  prepare-conda-env:

    steps:
      - run:
          name: update conda
          command: >
              conda update conda
      - run:
          name: add channel conda-forge
          command: >
              conda config --append channels conda-forge

      - run:
          name: install required packages
          command: >
              conda install pylint openexr simplejson orekit

      - run:
          name: update conda packages
          command: >
              conda update --all

  linting:
    steps:
      - checkout

      - run:
          name: lint
          command: >
              pylint blender_controller DidymosModelingMoonless_100kmRotDidymoon
            
      - run:
          name: notify test is finished
          command: echo "Test is completed!"

workflows:
  version: 2.1
  
  test:
      jobs:
        - prepare-conda-env
        - linting:
            requires:
              - prepare-conda-env
